<?php

namespace AppBundle\Repository;

/**
 * CroisiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CroisiereRepository extends \Doctrine\ORM\EntityRepository
{
}
